apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: your-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-container
        image: your-image:v1.0
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "UTC +530"  # Timezone
        - name: ENVIRONMENT
          value: "production"  # Environment
        - name: LOG_LEVEL
          value: "Debug"  # Logging level
        - name: DB_HOST
          value: "database-host"  # Database host
        - name: DB_PORT
          value: "5432"  # Database port
        - name: DB_USER
          value: "dbuser"  # Database user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password  # Database password from a secret
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: key  # API key from a secret
        - name: MAX_CONNECTIONS
          value: "100"  # Maximum connections
        - name: CACHE_SIZE
          value: "256MB"  # Cache size
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: "1024Mi
