---
- name: Use Facts Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display loaded facts
      debug:
        msg:
          - "App Version: {{ app_version }}"
          - "Database Host: {{ db_host }}"
          - "Database Port: {{ db_port }}"
          - "API Endpoint: {{ api_endpoint }}"
