---
- name: Use Facts Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display retrieved facts
      debug:
        msg:
          - "App Version: {{ app_version }}"
          - "Database Host: {{ db_host }}"
          - "Database Port: {{ db_port }}"
          - "API Endpoint: {{ api_endpoint }}"

    - name: Use retrieved facts (example task)
      debug:
        msg: "Connecting to database at {{ db_host }}:{{ db_port }}"
